/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.example.mydsl.ide.contentassist.antlr.internal.InternalMyDslParser;
import org.xtext.example.mydsl.services.MyDslGrammarAccess;

public class MyDslParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(MyDslGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, MyDslGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getZNotationModelAccess().getGroup(), "rule__ZNotationModel__Group__0");
			builder.put(grammarAccess.getZNotationModelAccess().getGroup_3(), "rule__ZNotationModel__Group_3__0");
			builder.put(grammarAccess.getZNotationModelAccess().getGroup_4(), "rule__ZNotationModel__Group_4__0");
			builder.put(grammarAccess.getZNotationModelAccess().getGroup_4_3(), "rule__ZNotationModel__Group_4_3__0");
			builder.put(grammarAccess.getSchemaAccess().getGroup(), "rule__Schema__Group__0");
			builder.put(grammarAccess.getSchemaAccess().getGroup_3(), "rule__Schema__Group_3__0");
			builder.put(grammarAccess.getSchemaAccess().getGroup_4(), "rule__Schema__Group_4__0");
			builder.put(grammarAccess.getSchemaAccess().getGroup_5(), "rule__Schema__Group_5__0");
			builder.put(grammarAccess.getSchemaAccess().getGroup_5_3(), "rule__Schema__Group_5_3__0");
			builder.put(grammarAccess.getSchemaStateAccess().getGroup(), "rule__SchemaState__Group__0");
			builder.put(grammarAccess.getSchemaStateAccess().getGroup_3(), "rule__SchemaState__Group_3__0");
			builder.put(grammarAccess.getSchemaStateAccess().getGroup_4(), "rule__SchemaState__Group_4__0");
			builder.put(grammarAccess.getSchemaStateAccess().getGroup_4_3(), "rule__SchemaState__Group_4_3__0");
			builder.put(grammarAccess.getRelationAccess().getGroup(), "rule__Relation__Group__0");
			builder.put(grammarAccess.getRelationAccess().getGroup_3(), "rule__Relation__Group_3__0");
			builder.put(grammarAccess.getRelationAccess().getGroup_4(), "rule__Relation__Group_4__0");
			builder.put(grammarAccess.getVariableAccess().getGroup(), "rule__Variable__Group__0");
			builder.put(grammarAccess.getVariableAccess().getGroup_3(), "rule__Variable__Group_3__0");
			builder.put(grammarAccess.getVariableAccess().getGroup_4(), "rule__Variable__Group_4__0");
			builder.put(grammarAccess.getVariableAccess().getGroup_5(), "rule__Variable__Group_5__0");
			builder.put(grammarAccess.getZNotationModelAccess().getModelNameAssignment_3_1(), "rule__ZNotationModel__ModelNameAssignment_3_1");
			builder.put(grammarAccess.getZNotationModelAccess().getSchemaAssignment_4_2(), "rule__ZNotationModel__SchemaAssignment_4_2");
			builder.put(grammarAccess.getZNotationModelAccess().getSchemaAssignment_4_3_1(), "rule__ZNotationModel__SchemaAssignment_4_3_1");
			builder.put(grammarAccess.getSchemaAccess().getSchemaTitleAssignment_3_1(), "rule__Schema__SchemaTitleAssignment_3_1");
			builder.put(grammarAccess.getSchemaAccess().getSchemastateAssignment_4_1(), "rule__Schema__SchemastateAssignment_4_1");
			builder.put(grammarAccess.getSchemaAccess().getRelationAssignment_5_2(), "rule__Schema__RelationAssignment_5_2");
			builder.put(grammarAccess.getSchemaAccess().getRelationAssignment_5_3_1(), "rule__Schema__RelationAssignment_5_3_1");
			builder.put(grammarAccess.getSchemaStateAccess().getStateTypeAssignment_3_1(), "rule__SchemaState__StateTypeAssignment_3_1");
			builder.put(grammarAccess.getSchemaStateAccess().getVariableAssignment_4_2(), "rule__SchemaState__VariableAssignment_4_2");
			builder.put(grammarAccess.getSchemaStateAccess().getVariableAssignment_4_3_1(), "rule__SchemaState__VariableAssignment_4_3_1");
			builder.put(grammarAccess.getRelationAccess().getRelationTypeAssignment_3_1(), "rule__Relation__RelationTypeAssignment_3_1");
			builder.put(grammarAccess.getRelationAccess().getRelatedToAssignment_4_1(), "rule__Relation__RelatedToAssignment_4_1");
			builder.put(grammarAccess.getVariableAccess().getNameAssignment_3_1(), "rule__Variable__NameAssignment_3_1");
			builder.put(grammarAccess.getVariableAccess().getValueAssignment_4_1(), "rule__Variable__ValueAssignment_4_1");
			builder.put(grammarAccess.getVariableAccess().getTypeAssignment_5_1(), "rule__Variable__TypeAssignment_5_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private MyDslGrammarAccess grammarAccess;

	@Override
	protected InternalMyDslParser createParser() {
		InternalMyDslParser result = new InternalMyDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public MyDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MyDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
