/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.formatting2;

import com.google.inject.Inject;
import java.util.Arrays;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.xbase.lib.Extension;
import org.xtext.example.mydsl.services.MyDslGrammarAccess;

@SuppressWarnings("all")
public class MyDslFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private MyDslGrammarAccess _myDslGrammarAccess;
  
  protected void _format(final /* ZNotationModel */Object zNotationModel, @Extension final IFormattableDocument document) {
    throw new Error("Unresolved compilation problems:"
      + "\nschema cannot be resolved"
      + "\nformat cannot be resolved");
  }
  
  protected void _format(final /* SchemaState */Object schemaState, @Extension final IFormattableDocument document) {
    throw new Error("Unresolved compilation problems:"
      + "\nvariable cannot be resolved"
      + "\nformat cannot be resolved");
  }
  
  public void format(final Object zNotationModel, final IFormattableDocument document) {
    if (zNotationModel instanceof XtextResource) {
      _format((XtextResource)zNotationModel, document);
      return;
    } else if (zNotationModel instanceof EObject) {
      _format((EObject)zNotationModel, document);
      return;
    } else if (zNotationModel == null) {
      _format((Void)null, document);
      return;
    } else if (zNotationModel != null) {
      _format(zNotationModel, document);
      return;
    } else if (zNotationModel != null) {
      _format(zNotationModel, document);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(zNotationModel, document).toString());
    }
  }
}
